### ISSUE TITLE
CropRatioType.Square not work on Android

### ISSUE THREAD

**Issue by Bbone19** [Xamarians/Xamarians.CropImage#1]
Although I am using CropRatioType.Square as parameter , I am still able to resize the crop panel as I want. I expected to have the ration 1:1 enforced.
 `CropImage(media.Path, Xamarians.CropImage.CropRatioType.Square)`

I did not test on IOs.
In case it is a bug, I believe I have a fix.

```C#
public Task<CropResult> CropImage(string imagePath, CropRatioType ratioType)
        {
            _tcs = new TaskCompletionSource<CropResult>();
            Intent intent = new Intent(_context, typeof(CropImageActivity));
            intent.PutExtra("image-path", imagePath);
            intent.PutExtra("scale", false);
            
            if(ratioType == CropRatioType.Square)
            {
                intent.PutExtra("aspectX", 1);
                intent.PutExtra("aspectY", 1);
            }
            _context.StartActivity(intent);
            return _tcs.Task;
        }
```

**Comment by phamthanhtong** [comment]
@Bbone19 I have the same problem, CropRatioType.Square need to fix.
@Xamarians Could you pull above code soon please?

**Comment by Xamarians** [comment]
The Issue has been fixed.
Thanks for reporting it.
Here is the link to the latest version :
https://www.nuget.org/packages/Xamarians.CropImage/1.0.5
