### ISSUE TITLE
How to convert CropImageResult to byte[]?

### ISSUE THREAD

**Issue by wahab2512** [Xamarians/Xamarians.CropImage#5]
var cropResult = await CropImageService.Instance.CropImage(filePath, CropRatioType.Square);
how to convert cropResult to byte[]?

**Comment by Xamarians** [comment]
@wahab2512 [Convert ImagePath to byte[]](https://social.msdn.microsoft.com/Forums/en-US/30c41723-33b2-4ab5-a2e2-4f7fe625dd9b/converting-to-byte-array-from-image-path?forum=csharplanguage). You will get image path from "cropResult.FilePath".
